(()=>{
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;
const videos=[...document.querySelectorAll('video[data-ambient]')];
const visible=new Set();const safePlay=v=>{if(!paused){if(!v.getAttribute('src'))v.src=v.dataset.ambient;v.muted=true;v.play().catch(()=>{});}};
const io=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){visible.add(e.target);safePlay(e.target)}else{visible.delete(e.target);e.target.pause()}}},{threshold:.08});videos.forEach(v=>io.observe(v));
const control=document.querySelector('#motion-control');function applyMotion(){videos.forEach(v=>paused?v.pause():visible.has(v)&&safePlay(v));if(control){control.setAttribute('aria-pressed',String(paused));control.setAttribute('aria-label',paused?'Play ambient films':'Pause ambient films');control.innerHTML=paused?'▷ <span>Play motion</span>':'Ⅱ <span>Pause motion</span>';}}control?.addEventListener('click',()=>{paused=!paused;applyMotion()});reduced.addEventListener('change',e=>{paused=e.matches;applyMotion()});applyMotion();document.addEventListener('visibilitychange',()=>{if(document.hidden)videos.forEach(v=>v.pause());else applyMotion()});
const scenes={nyc:['event-design/assets/curated/loops/nyc-event.mp4','event-design/assets/curated/posters/nyc-event.jpg'],rooftop:['event-design/assets/curated/loops/rooftop-pour.mp4','event-design/assets/curated/posters/rooftop-pour.jpg'],office:['event-design/assets/curated/loops/buzzfeed-office.mp4','event-design/assets/curated/posters/nyc-event.jpg']};
const player=document.querySelector('#scene-video');let sequence=0;document.querySelectorAll('[data-scene]').forEach(b=>b.addEventListener('click',()=>{const scene=scenes[b.dataset.scene];if(!scene||b.getAttribute('aria-pressed')==='true')return;sequence++;const ticket=sequence;document.querySelectorAll('[data-scene]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));player.style.opacity='0';setTimeout(()=>{if(ticket!==sequence)return;player.poster=scene[1];player.dataset.ambient=scene[0];player.src=scene[0];player.load();if(!paused)safePlay(player);player.style.opacity='1'},reduced.matches?0:220)}));
if(!reduced.matches){const reveal=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('is-in');reveal.unobserve(e.target)}},{threshold:.08});document.querySelectorAll('.cinema-intro,.feature-copy,.section-head,.editorial-card,.steps article,.gallery-grid article,.price-card,.closing').forEach(e=>{e.classList.add('reveal-ready');reveal.observe(e)})}
})();
